### ISSUE TITLE
nmap-vulners submodule - out of date?

### ISSUE THREAD

**Issue by mh-2112** [center-for-threat-informed-defense/caldera_pathfinder#24]
Hello! 

It seems the sumbodule link for your nmap-vulners is broken. Version mismatch perhaps? 

caldera_pathfinder/scanners/nmap/scripts/

**Comment by wbooth** [comment]
Thanks, we'll take a look and fix!

**Comment by mrengstrom** [comment]
The link is setup for ssh pulling and not https.  I can swap it around as both are public repos, but if you also setup a ssh key with github it will pull as well.
