### ISSUE TITLE
data_svc.py:349 _verify_adversary_profiles

### ISSUE THREAD

**Issue by wyc7** [center-for-threat-informed-defense/caldera_pathfinder#31]
I installed pathfinder on caldera 3.0.0, and when I started caldera with the command "python3 server.py --insecure", a warning appeared.

Screenshot：
![image](https://user-images.githubusercontent.com/48666541/114332971-d3b2f180-9b79-11eb-8a1a-3a68c5029a8e.png)

Does it have any impact on subsequent operations? How to eliminate the warning?

**Comment by wbooth** [comment]
https://github.com/center-for-threat-informed-defense/caldera_pathfinder/pull/32 thanks this should be resolved through this PR
