### ISSUE TITLE
Unable to show vulnerability

### ISSUE THREAD

**Issue by Difficultcl** [center-for-threat-informed-defense/caldera_pathfinder#33]
Hello，I found that when scanning for vulnerabilities in the pathfinder plugin, the web page did not show the scanned vulnerabilities, but running the Nmap scan locally did.

![image](https://user-images.githubusercontent.com/38584419/115359062-e029f080-a1f0-11eb-9f7e-53a4699cee51.png)
![image](https://user-images.githubusercontent.com/38584419/115359028-d607f200-a1f0-11eb-9cbf-30549267f6c1.png)

![image](https://user-images.githubusercontent.com/38584419/115357988-cc31bf00-a1ef-11eb-92c2-b81dcf43a9e3.png)
![image](https://user-images.githubusercontent.com/38584419/115358055-dc499e80-a1ef-11eb-9763-83418b4f67d5.png)
![image](https://user-images.githubusercontent.com/38584419/115358107-e8356080-a1ef-11eb-8407-95dbf92c3c66.png)

**Comment by mrengstrom** [comment]
So, one thing I can comment on is that what you ran from the command line is not going to match what you ran from pathfinder.

I can see from the command line you ran with `--script=vuln`, this is the overarching category of all nmap vulnerability scripts.  In caldera you ran the specific subset script which is vulners (or nmap-vulners if you use the repository name).  So the vulnerabilities you found may not be ones that are flagged by that script set.  you can duplicate the caldera output by running this from the commandline:
`nmap 192.168.10.137/24 --script=vulners`
https://nmap.org/nsedoc/categories/vuln.html

Though as you can see based on your scan, it may be beneficial for us to allow category scanning and not just based on scripts found and populated in the `./scanners/nmap/scripts` folder for caldera.

I just pushed up a small PR for a change that would populate out all the possible scripts available for nmap and allow them to be ran, you can pull the branch `nmap_builtin_scripts` and run `vuln` or any of the specific scripts (smb-vuln-ms17-010) that flagged a CVE for you to make sure you get the same output you saw in your commandline execution

**Comment by Difficultcl** [comment]
Thank you for your reply,but there are new problems when I try to pull the branch nmap_builtin_scripts and run vuln.
![image](https://user-images.githubusercontent.com/38584419/119355499-ee7b9880-bcd7-11eb-926c-d2e685186b18.png)
![image](https://user-images.githubusercontent.com/38584419/119355590-06ebb300-bcd8-11eb-9b63-365f1d63958a.png)
ERROR (nmap.py:28 parse) exception when parsing nmap results xml: ParseError('not well-formed (invalid token): line 32, column 0')

**Comment by mrengstrom** [comment]
@Difficultcl 
If there is no sensitive data in the scan can you post the nmap xml report from the scan?  It should be located in the `plugins/pathfinder/data/reports` directory

I was unable to reproduce the parsing failure, but it may be something specific to the format of the xml file.
Also the xml file will have the nmap version (yours looks to be 7.91) and some other details as well that would be helpful for going through and trying to reproduce and resolve this.
