### ISSUE TITLE
c_cve.py errors

### ISSUE THREAD

**Issue by jasonegorman** [center-for-threat-informed-defense/caldera_pathfinder#40]
When adding Pathfinder plugin to working Ubuntu 20.04 Caldera 3.1.0 or 4.0.0-Alpha builds, encountered the attached error, referencing c_cve.py.  If I copy c_cve.py from pathfinder/app/objects/ to caldera/app/objects, Pathfinder appears to work fine.  Looking at caldera/plugins/pathfinder/app/enrichment/cve.py, in line 11 it calls to "from app.objects.c_cve import CVE".  If I edit the line to be "from plugins.pathfinder.app.objects.c_cve import CVE", Pathfinder plugin generates no errors on Caldera server version 3.1.0 or 4.0.0-Alpha and appears to operate correctly.
![pathfinder_error](https://user-images.githubusercontent.com/94212968/141607575-be60712c-be9c-4c39-b655-20839f5e4b67.png)

**Comment by elegantmoose** [comment]
@jasonegorman - yes, fix is already in a PR in review, but appreciate bringing the bug to our attention.

**Comment by jasonegorman** [comment]
Awesome, thanks for the update.  Sorry I didn't look at PR 39 before
opening issue.

**Comment by elegantmoose** [comment]
@jasonegorman - Not at all. We really appreciate any bug notifications.
