### ISSUE TITLE
Nmap parsing error with pathfinder_gui.py

### ISSUE THREAD

**Issue by alaanasser00** [center-for-threat-informed-defense/caldera_pathfinder#45]
Hey guys. I'm using Caldera v4.0.0 and I added pathfinder plugin. I made a vulnerable vm (https://github.com/timurozkul/HeartBleed) to test it with the ssl-heartbleed.nse script but I get an error that tells me to ensure that the target has a CVE. I tried it manually with nmap and it worked. Another error that I get is on the terminal. Can anybody help me solve this problem? Thank you so much.
![image](https://user-images.githubusercontent.com/42778519/153428434-fde0d27f-171f-403f-8bb8-4023a5d36233.png)

**Comment by CDJellen** [comment]
This issues was resolved by the most recent PR (#49).  If the issue persists for you, please feel free to re-open this issue.  Thank you for bringing the parsing issue to the team's attention.
