### ISSUE TITLE
error importing plugin=pathfinder, no module named 'networkx'

### ISSUE THREAD

**Issue by blockanz** [center-for-threat-informed-defense/caldera_pathfinder#55]
Trying to use the pathfinder plugin with Caldera Docker image and getting the error:

error importing plugin=pathfinder, no module named 'networkx'

Have correctly cloned repository into caldera/plugins/pathfinder

ran pip3 install -r requirements.txt in caldera/plugins/pathfinder subdir

Rebuilt docker caldera docker image but still getting the above.

Anyone have any ideas?

Thanks

**Comment by elegantmoose** [comment]
Hey @blockanz - when you build the docker image, are you seeing output that the `networkx` package is actually being installed successfully?

**Comment by blockanz** [comment]
@elegantmoose I have just re-run the docker build and cannot find anything relating to networkx package at all. I'm not convinced it is being installed as part of the build (at least I can see no evidence to suggest it is).

**Comment by elegantmoose** [comment]
@blockanz Sorry I have not had time to investigate further but can you try adding `networkx` to the Caldera `requirements.txt` file and then rebuilding the docker image?

**Comment by mehaase** [comment]
I noticed networkx is now included in requirements.txt, and I just added a line to the installation instructions to pip install the requirements.
