### ISSUE TITLE
error when rendering after selecting nmap from Pathfinder drop-down

### ISSUE THREAD

**Issue by scoobyduo** [center-for-threat-informed-defense/caldera_pathfinder#56]
Selecting the 'nmap' scanner from the Caldera GUI with Pathfinder plugin installed results in a Javascript Reference Error 

```
pathfinder.js:222 ReferenceError: validateFormState is not defined
 at pathfinder.js:207:9
(anonymous) @ pathfinder.js:222
```

```
function setupScannerSection(){
.....
.....
        validateFormState(response.enabled, '#startScan')
```

Would appear the validateFormState function is not defined

*Note : Just cloned the code direct into Caldera plugin - no docker etc

**Comment by mehaase** [comment]
This should be fixed in #58 -- please let us know if you're still having an issue with this. I'll make a tag and release containing this fix shortly.
