### ISSUE TITLE
error setting up scanner

### ISSUE THREAD

**Issue by evilprime** [center-for-threat-informed-defense/caldera_pathfinder#57]
Hi, 

after the steps which are needed to get this up and running (i think), when i go to the plugins and select pathfinder and initiate a new scan i get the error 'error setting up scanner' 

any pointers on this issue?

regards

Lennart

**Comment by L015H4CK** [comment]
This was a known issue and should be fixed by now. See https://github.com/mitre/caldera/issues/2650.
