### ISSUE TITLE
Plugin update issue

### ISSUE THREAD

**Issue by bali-84** [center-for-threat-informed-defense/caldera_pathfinder#64]
I got this message how can i update the plugin

Warning: You're currently using the legacy plugin interface for pathfinder. While it might function, we cannot guarantee its full compatibility or stability. For the best experience, we recommend updating to the latest UI version

**Comment by elegantmoose** [comment]
Unfortunately, Pathfinder is not maintained by the Caldera team and to my knowledge no one else actively maintains the repo.

As such, to update, you would need to manually refactor the plugin interface to match Caldera's Vue framework. Not sure of the level of effort, but you could look at other plugins for examples.
